# Generated by Django 3.1.4 on 2020-12-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201231_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='file',
            new_name='fileupload',
        ),
        migrations.AlterField(
            model_name='academic',
            name='academic_name',
            field=models.CharField(max_length=200),
        ),
    ]
