# Generated by Django 3.1.4 on 2021-01-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_employment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic',
            new_name='class_routine',
        ),
        migrations.RenameField(
            model_name='class_routine',
            old_name='academic_name',
            new_name='class_routine_name',
        ),
    ]
